



    includelib \masm64\lib64\msvcrt.lib
    externdef scanf: near
    externdef printf: near
    externdef fopen: near
    externdef fwrite: near
    externdef fclose: near
    externdef fseek: near
    externdef ftell: near
    externdef rewind: near
    externdef fread: near
    externdef free: near
    externdef getchar: near
    externdef system: near
    externdef strlen: near
    externdef exit: near
    externdef sprintf: near
    externdef fgetc: near
    externdef getch: near
    externdef strcpy: near
    externdef strcat: near
    externdef atof: near
    externdef atol: near
    externdef atoi: near
    externdef ftoa: near
    externdef strtok: near
    externdef fgets: near
    externdef memset: near
    ;externdef malloc: near
    ;externdef relloc: near







    
    